name: 'Get Matrix for Shopware versions'
description: 'Gets a GitHub Action Matrix array for Shopware versions depending on given version constraint'
author: 'tinect'
branding:
  icon: 'shuffle'
  color: 'blue'
inputs:
  versionConstraint:
    required: true
    description: 'Version constraint for Shopware'
    default: '~6.6.0'
  allowEol:
    required: false
    description: 'Determine whether to include EOL versions of Shopware and PHP'
    default: 'false'
  justMinMaxShopware:
    required: false
    description: 'Determine whether to only include the min and max version of Shopware - otherwise all minor versions in between are included.'
    default: 'false'
  allowShopwareNext:
    required: false
    description: 'Determine whether to include unreleased version of Shopware - respecting the version constraint.'
    default: 'false'
  allowShopwareRC:
    required: false
    description: 'Determine whether to include release candidates of Shopware.'
    default: 'false'
  includePhpVersion:
    required: false
    description: 'Determine whether to include PHP version per entry.'
    default: 'true'
outputs:
  matrix:
    description: 'GitHub Action Matrix'
runs:
  using: 'node20'
  main: 'dist/index.js'